create table games(
	id integer primary key,
	game_date text, 
	home_team text, 
	away_team text, 
	w_l text, 
	home_team_runs integer, 
	away_team_runs integer,
        inn integer, 
	home_wl str,
	team_rank int, 
	gb str, 
	win str, 
	loss str, 
	save str, 
	time str, 
	d_n str,
        attendance float, 
	c_li float, 
	home_streak str, 
	orig_scheduled float, 
	home_game bool,
	year int)
