PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "teams" ("id" INTEGER NOT NULL PRIMARY KEY, "abbreviation" TEXT, "city" TEXT, "league" TEXT, "division" TEXT, "team_id" INTEGER, "team_name" TEXT, "stadium_type" TEXT);
INSERT INTO teams VALUES(1,'Ana',NULL,'AL','AL West','','Los Angeles Angels of Anaheim','Open');
INSERT INTO teams VALUES(2,'Ari',NULL,'NL','NL West',NULL,NULL,NULL);
INSERT INTO teams VALUES(3,'Atl',NULL,'NL','NL East',NULL,'Atlanta Braves',NULL);
INSERT INTO teams VALUES(4,'Bal',NULL,'AL','AL East',NULL,'Baltimore Orioles',NULL);
INSERT INTO teams VALUES(5,'Bos',NULL,'AL','AL East',NULL,'Boston Red Sox',NULL);
INSERT INTO teams VALUES(6,'ChC',NULL,'NL','NL Central',NULL,'Chicago Cubs',NULL);
INSERT INTO teams VALUES(7,'ChW',NULL,'AL','AL Central',NULL,'Chicago White Sox',NULL);
INSERT INTO teams VALUES(8,'Cin',NULL,'NL','NL Central',NULL,'Cincinnati Reds',NULL);
INSERT INTO teams VALUES(9,'Cle',NULL,'AL','AL Central',NULL,'Cleveland Indians',NULL);
INSERT INTO teams VALUES(10,'Col',NULL,'NL','NL West',NULL,NULL,NULL);
INSERT INTO teams VALUES(11,'Det',NULL,'AL','AL Central',NULL,'Detroit Tigers',NULL);
INSERT INTO teams VALUES(12,'Fla',NULL,'NL','NL East',NULL,'Miami Marlins',NULL);
INSERT INTO teams VALUES(13,'Hou',NULL,'AL','AL West',NULL,'Houston Astros',NULL);
INSERT INTO teams VALUES(14,'Kan',NULL,'AL','AL Central',NULL,'Kansas City Royals',NULL);
INSERT INTO teams VALUES(15,'Los',NULL,'NL','NL West',NULL,'Los Angeles Dodgers',NULL);
INSERT INTO teams VALUES(16,'Mil',NULL,'NL','NL Central',NULL,'Milwaukee Brewers',NULL);
INSERT INTO teams VALUES(17,'Min',NULL,'AL','AL Central',NULL,'Minnesota Twins',NULL);
INSERT INTO teams VALUES(18,'NYM',NULL,'NL','NL East',NULL,'New York Mets',NULL);
INSERT INTO teams VALUES(19,'NYY',NULL,'AL','AL East',NULL,'New York Yankees',NULL);
INSERT INTO teams VALUES(20,'Oak',NULL,'AL','AL West',NULL,'Oakland A''s',NULL);
INSERT INTO teams VALUES(21,'Phi',NULL,'NL','NL East',NULL,'Philadelphia Phillies',NULL);
INSERT INTO teams VALUES(22,'Pit',NULL,'NL','NL Central',NULL,'Pittsburgh Pirates',NULL);
INSERT INTO teams VALUES(23,'Sdg',NULL,'NL','NL West',NULL,'San Diego Padres',NULL);
INSERT INTO teams VALUES(24,'Sea',NULL,'AL','AL West',NULL,'Seattle Mariners',NULL);
INSERT INTO teams VALUES(25,'Sfo',NULL,'NL','NL West',NULL,'San Francisco Giants','Open');
INSERT INTO teams VALUES(26,'StL',NULL,'NL','NL Central',NULL,'St. Louis Cardinals',NULL);
INSERT INTO teams VALUES(27,'Tam',NULL,'AL','AL East',NULL,'Tampa Bay Rays',NULL);
INSERT INTO teams VALUES(28,'Tex',NULL,'AL','AL West',NULL,'Texas Rangers',NULL);
INSERT INTO teams VALUES(29,'Tor',NULL,'AL','AL East',NULL,'Toronto Blue Jays','Dome');
INSERT INTO teams VALUES(30,'Was',NULL,'NL','NL East',NULL,'Washington Nationals',NULL);
COMMIT;
